"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SearchContactBy = exports.eMeasure = exports.eReportTimePeriod = exports.eReportFilterBy = exports.eApptStatus = exports.eMailingStatus = exports.eTaskStatus = exports.eCalenderView = exports.eGoalTypeCategory = exports.eGoalType = exports.eDDField = exports.eCalCalendar = exports.eApptCategory = exports.eTaskPriority = exports.eTaskCategory = exports.eUploadContactActionToTake = exports.eEditType = exports.CreateExportFor = exports.eExportRequestStatus = exports.eExportRequestObjectType = exports.eBillingViewMode = exports.eColor = exports.eCompanySettings = exports.webFormAction = exports.eLeadSettings = exports.eAppointmentSettings = exports.eClassCodes = exports.eFeatures = exports.eSOSCStatus = exports.eFieldType = exports.eUserPermissions = exports.eOSStatus = exports.eFieldStatus = exports.eReadWrite = exports.eUserRole = exports.eCLPRole = exports.eSectionCompany = exports.eSection = exports.eSectionLead = exports.eServiceType = exports.eCLPCompanyStatus = exports.eTicketStatus = exports.eNoteEmailToChoice = exports.eNoteStatus = exports.eNoteOwnerType = exports.eDocumentCategory = exports.eTicketCategory = exports.eOSAddressType = void 0;
var eOSAddressType;
(function (eOSAddressType) {
    eOSAddressType[eOSAddressType["None"] = 0] = "None";
    eOSAddressType[eOSAddressType["Business"] = 1] = "Business";
    eOSAddressType[eOSAddressType["Home"] = 2] = "Home";
    eOSAddressType[eOSAddressType["Other"] = 3] = "Other";
})(eOSAddressType = exports.eOSAddressType || (exports.eOSAddressType = {}));
var eTicketCategory;
(function (eTicketCategory) {
    eTicketCategory[eTicketCategory["Unknown"] = 0] = "Unknown";
    eTicketCategory[eTicketCategory["Question"] = 1] = "Question";
    eTicketCategory[eTicketCategory["Need_Help"] = 2] = "Need_Help";
    eTicketCategory[eTicketCategory["Report_a_problem"] = 3] = "Report_a_problem";
    eTicketCategory[eTicketCategory["Idea_for_new_feature"] = 4] = "Idea_for_new_feature";
    eTicketCategory[eTicketCategory["Urgent"] = 5] = "Urgent";
    eTicketCategory[eTicketCategory["Request_Training"] = 6] = "Request_Training";
})(eTicketCategory = exports.eTicketCategory || (exports.eTicketCategory = {}));
var eDocumentCategory;
(function (eDocumentCategory) {
    eDocumentCategory[eDocumentCategory["Unknown"] = 0] = "Unknown";
    eDocumentCategory[eDocumentCategory["Appointment"] = 1] = "Appointment";
    eDocumentCategory[eDocumentCategory["Contact"] = 2] = "Contact";
    eDocumentCategory[eDocumentCategory["Lead"] = 3] = "Lead";
    eDocumentCategory[eDocumentCategory["Mailing"] = 4] = "Mailing";
    eDocumentCategory[eDocumentCategory["Personal"] = 5] = "Personal";
    eDocumentCategory[eDocumentCategory["Company"] = 6] = "Company";
    eDocumentCategory[eDocumentCategory["Task"] = 9] = "Task";
})(eDocumentCategory = exports.eDocumentCategory || (exports.eDocumentCategory = {}));
var eNoteOwnerType;
(function (eNoteOwnerType) {
    eNoteOwnerType[eNoteOwnerType["Unknown"] = 0] = "Unknown";
    eNoteOwnerType[eNoteOwnerType["Personal"] = 1] = "Personal";
    eNoteOwnerType[eNoteOwnerType["Contact"] = 2] = "Contact";
    eNoteOwnerType[eNoteOwnerType["Lead"] = 3] = "Lead";
    eNoteOwnerType[eNoteOwnerType["Company"] = 4] = "Company";
    eNoteOwnerType[eNoteOwnerType["Project"] = 5] = "Project";
    eNoteOwnerType[eNoteOwnerType["LinkGroup"] = 6] = "LinkGroup";
    eNoteOwnerType[eNoteOwnerType["Note"] = 7] = "Note";
    eNoteOwnerType[eNoteOwnerType["Invoice"] = 8] = "Invoice";
    eNoteOwnerType[eNoteOwnerType["Mailing"] = 11] = "Mailing";
})(eNoteOwnerType = exports.eNoteOwnerType || (exports.eNoteOwnerType = {}));
var eNoteStatus;
(function (eNoteStatus) {
    eNoteStatus[eNoteStatus["Unknown"] = -1] = "Unknown";
    eNoteStatus[eNoteStatus["Completed"] = 0] = "Completed";
    eNoteStatus[eNoteStatus["Pending"] = 1] = "Pending";
    eNoteStatus[eNoteStatus["InProcessing"] = 2] = "InProcessing";
    eNoteStatus[eNoteStatus["Failed"] = 3] = "Failed";
    eNoteStatus[eNoteStatus["ToBeDeleted"] = 9] = "ToBeDeleted";
})(eNoteStatus = exports.eNoteStatus || (exports.eNoteStatus = {}));
var eNoteEmailToChoice;
(function (eNoteEmailToChoice) {
    eNoteEmailToChoice[eNoteEmailToChoice["None"] = 0] = "None";
    eNoteEmailToChoice[eNoteEmailToChoice["Contact"] = 1] = "Contact";
    eNoteEmailToChoice[eNoteEmailToChoice["User"] = 2] = "User";
    eNoteEmailToChoice[eNoteEmailToChoice["Other"] = 3] = "Other";
    eNoteEmailToChoice[eNoteEmailToChoice["Link"] = 4] = "Link";
    eNoteEmailToChoice[eNoteEmailToChoice["Fax2Mail"] = 5] = "Fax2Mail";
    eNoteEmailToChoice[eNoteEmailToChoice["ContactAllEmails"] = 6] = "ContactAllEmails";
})(eNoteEmailToChoice = exports.eNoteEmailToChoice || (exports.eNoteEmailToChoice = {}));
var eTicketStatus;
(function (eTicketStatus) {
    eTicketStatus[eTicketStatus["AllOpenOrUnread"] = 9] = "AllOpenOrUnread";
    eTicketStatus[eTicketStatus["Unknown"] = 0] = "Unknown";
    eTicketStatus[eTicketStatus["Active"] = 1] = "Active";
    eTicketStatus[eTicketStatus["Being_Handled"] = 2] = "Being_Handled";
    eTicketStatus[eTicketStatus["Resolved"] = 3] = "Resolved";
    eTicketStatus[eTicketStatus["Under_Consideration"] = 4] = "Under_Consideration";
    eTicketStatus[eTicketStatus["User_Feedback_Required"] = 5] = "User_Feedback_Required";
})(eTicketStatus = exports.eTicketStatus || (exports.eTicketStatus = {}));
var eCLPCompanyStatus;
(function (eCLPCompanyStatus) {
    eCLPCompanyStatus[eCLPCompanyStatus["DoesNotExist"] = 0] = "DoesNotExist";
    eCLPCompanyStatus[eCLPCompanyStatus["IsValid"] = 1] = "IsValid";
    eCLPCompanyStatus[eCLPCompanyStatus["OnIntro"] = 2] = "OnIntro";
    eCLPCompanyStatus[eCLPCompanyStatus["Expired"] = 3] = "Expired";
    eCLPCompanyStatus[eCLPCompanyStatus["Disabled"] = 4] = "Disabled";
    eCLPCompanyStatus[eCLPCompanyStatus["FreeAccount"] = 5] = "FreeAccount";
})(eCLPCompanyStatus = exports.eCLPCompanyStatus || (exports.eCLPCompanyStatus = {}));
var eServiceType;
(function (eServiceType) {
    eServiceType[eServiceType["Unknown"] = 0] = "Unknown";
    eServiceType[eServiceType["DailyServ"] = 1] = "DailyServ";
    eServiceType[eServiceType["EmailServ"] = 2] = "EmailServ";
    eServiceType[eServiceType["ParserServ"] = 3] = "ParserServ";
    eServiceType[eServiceType["DropBoxServ"] = 4] = "DropBoxServ";
    eServiceType[eServiceType["ReminderServ"] = 5] = "ReminderServ";
    eServiceType[eServiceType["ExportServ"] = 6] = "ExportServ";
    eServiceType[eServiceType["GSyncServ"] = 7] = "GSyncServ";
    eServiceType[eServiceType["TxtMsgServ"] = 8] = "TxtMsgServ";
    eServiceType[eServiceType["VoiceServ"] = 9] = "VoiceServ";
    eServiceType[eServiceType["EvolveLeadServ"] = 10] = "EvolveLeadServ";
    eServiceType[eServiceType["TxtMsgCampaignServ"] = 11] = "TxtMsgCampaignServ";
    eServiceType[eServiceType["InventHelpLeadServ"] = 12] = "InventHelpLeadServ";
})(eServiceType = exports.eServiceType || (exports.eServiceType = {}));
var eSectionLead;
(function (eSectionLead) {
    eSectionLead[eSectionLead["General"] = 0] = "General";
    eSectionLead[eSectionLead["CustomDateFields"] = 1] = "CustomDateFields";
    eSectionLead[eSectionLead["CustomTextFields"] = 2] = "CustomTextFields";
    eSectionLead[eSectionLead["AdditionalMultilineTextFields"] = 3] = "AdditionalMultilineTextFields";
    eSectionLead[eSectionLead["RevenueRelatedFields"] = 4] = "RevenueRelatedFields";
    eSectionLead[eSectionLead["CustomMoneyFields"] = 5] = "CustomMoneyFields";
    eSectionLead[eSectionLead["CustomClassificationDropDownFields"] = 6] = "CustomClassificationDropDownFields";
    eSectionLead[eSectionLead["CustomClassificationCheckboxFields"] = 7] = "CustomClassificationCheckboxFields";
    eSectionLead[eSectionLead["None"] = -1] = "None";
})(eSectionLead = exports.eSectionLead || (exports.eSectionLead = {}));
var eSection;
(function (eSection) {
    eSection[eSection["System"] = 0] = "System";
    eSection[eSection["Communication"] = 1] = "Communication";
    eSection[eSection["Address"] = 2] = "Address";
    eSection[eSection["AddtionalInformation"] = 3] = "AddtionalInformation";
    eSection[eSection["ClassificationDropDown"] = 4] = "ClassificationDropDown";
    eSection[eSection["ClassificationCheckBox"] = 5] = "ClassificationCheckBox";
    eSection[eSection["Comments"] = 6] = "Comments";
    eSection[eSection["ImportantDates"] = 7] = "ImportantDates";
    eSection[eSection["MoreFields"] = 8] = "MoreFields";
    eSection[eSection["General"] = 9] = "General";
})(eSection = exports.eSection || (exports.eSection = {}));
var eSectionCompany;
(function (eSectionCompany) {
    eSectionCompany[eSectionCompany["General"] = 1] = "General";
    eSectionCompany[eSectionCompany["AddtionalInformation"] = 2] = "AddtionalInformation";
    eSectionCompany[eSectionCompany["Communication"] = 3] = "Communication";
    eSectionCompany[eSectionCompany["ClassificationDropDown"] = 4] = "ClassificationDropDown";
    eSectionCompany[eSectionCompany["ClassificationCheckBox"] = 5] = "ClassificationCheckBox";
    eSectionCompany[eSectionCompany["Comments"] = 6] = "Comments";
})(eSectionCompany = exports.eSectionCompany || (exports.eSectionCompany = {}));
var eCLPRole;
(function (eCLPRole) {
    eCLPRole[eCLPRole["StratusExpress"] = 0] = "StratusExpress";
    eCLPRole[eCLPRole["Stratus"] = 1] = "Stratus";
    eCLPRole[eCLPRole["Cirrus"] = 2] = "Cirrus";
    eCLPRole[eCLPRole["Nimbus"] = 3] = "Nimbus";
    eCLPRole[eCLPRole["Unknown"] = 9] = "Unknown";
})(eCLPRole = exports.eCLPRole || (exports.eCLPRole = {}));
var eUserRole;
(function (eUserRole) {
    eUserRole[eUserRole["None"] = 0] = "None";
    eUserRole[eUserRole["General"] = 1] = "General";
    eUserRole[eUserRole["Manager"] = 2] = "Manager";
    eUserRole[eUserRole["Administrator"] = 3] = "Administrator";
    eUserRole[eUserRole["SuperUser"] = 4] = "SuperUser";
    eUserRole[eUserRole["CLPAdminUser"] = 5] = "CLPAdminUser";
})(eUserRole = exports.eUserRole || (exports.eUserRole = {}));
var eReadWrite;
(function (eReadWrite) {
    eReadWrite[eReadWrite["None"] = 0] = "None";
    eReadWrite[eReadWrite["ViewOnly"] = 1] = "ViewOnly";
    eReadWrite[eReadWrite["ViewAndEdit"] = 2] = "ViewAndEdit";
})(eReadWrite = exports.eReadWrite || (exports.eReadWrite = {}));
var eFieldStatus;
(function (eFieldStatus) {
    eFieldStatus[eFieldStatus["Show"] = 0] = "Show";
    eFieldStatus[eFieldStatus["ShowMandatory"] = 1] = "ShowMandatory";
    eFieldStatus[eFieldStatus["Hide"] = 2] = "Hide";
})(eFieldStatus = exports.eFieldStatus || (exports.eFieldStatus = {}));
var eOSStatus;
(function (eOSStatus) {
    eOSStatus[eOSStatus["Disabled"] = 0] = "Disabled";
    eOSStatus[eOSStatus["Allowed"] = 1] = "Allowed";
    eOSStatus[eOSStatus["Downloaded"] = 2] = "Downloaded";
    eOSStatus[eOSStatus["Activated"] = 3] = "Activated";
})(eOSStatus = exports.eOSStatus || (exports.eOSStatus = {}));
var eUserPermissions;
(function (eUserPermissions) {
    eUserPermissions[eUserPermissions["Disabled"] = 0] = "Disabled";
    eUserPermissions[eUserPermissions["Active"] = 1] = "Active";
    eUserPermissions[eUserPermissions["Unknown"] = 9] = "Unknown";
})(eUserPermissions = exports.eUserPermissions || (exports.eUserPermissions = {}));
var eFieldType;
(function (eFieldType) {
    eFieldType[eFieldType["Textbox"] = 0] = "Textbox";
    eFieldType[eFieldType["CheckBox"] = 1] = "CheckBox";
    eFieldType[eFieldType["Dropdown"] = 2] = "Dropdown";
    eFieldType[eFieldType["None"] = 3] = "None";
    eFieldType[eFieldType["Combobox"] = 4] = "Combobox";
    eFieldType[eFieldType["Date"] = 5] = "Date";
    eFieldType[eFieldType["MultiLineTextbox"] = 6] = "MultiLineTextbox";
})(eFieldType = exports.eFieldType || (exports.eFieldType = {}));
var eSOSCStatus;
(function (eSOSCStatus) {
    eSOSCStatus[eSOSCStatus["New"] = 0] = "New";
    eSOSCStatus[eSOSCStatus["Draft"] = 1] = "Draft";
    eSOSCStatus[eSOSCStatus["Pending"] = 2] = "Pending";
    eSOSCStatus[eSOSCStatus["Signed"] = 3] = "Signed";
    eSOSCStatus[eSOSCStatus["Expired"] = 4] = "Expired";
})(eSOSCStatus = exports.eSOSCStatus || (exports.eSOSCStatus = {}));
var eFeatures;
(function (eFeatures) {
    eFeatures[eFeatures["None"] = 0] = "None";
    eFeatures[eFeatures["ContactCreate"] = 1] = "ContactCreate";
    eFeatures[eFeatures["ContactList"] = 2] = "ContactList";
    eFeatures[eFeatures["AutomationProcess"] = 3] = "AutomationProcess";
    eFeatures[eFeatures["Configuration"] = 4] = "Configuration";
    eFeatures[eFeatures["AccountSetup"] = 5] = "AccountSetup";
    eFeatures[eFeatures["RoleSetup"] = 6] = "RoleSetup";
    eFeatures[eFeatures["Usersetup"] = 7] = "Usersetup";
    eFeatures[eFeatures["SecuritySettings"] = 8] = "SecuritySettings";
    eFeatures[eFeatures["TextMessageSettings"] = 9] = "TextMessageSettings";
    eFeatures[eFeatures["CompanyModuleSettings"] = 10] = "CompanyModuleSettings";
    eFeatures[eFeatures["ContactModuleSettings"] = 11] = "ContactModuleSettings";
    eFeatures[eFeatures["LeadModuleSettings"] = 12] = "LeadModuleSettings";
    eFeatures[eFeatures["AppointmentNoteandMailingSettings"] = 13] = "AppointmentNoteandMailingSettings";
    eFeatures[eFeatures["TagSettings"] = 14] = "TagSettings";
    eFeatures[eFeatures["VoiceSettings"] = 15] = "VoiceSettings";
    eFeatures[eFeatures["CompanySetup"] = 16] = "CompanySetup";
    eFeatures[eFeatures["WebformManager"] = 17] = "WebformManager";
    eFeatures[eFeatures["TeamOfficeSetup"] = 18] = "TeamOfficeSetup";
    eFeatures[eFeatures["SOAccountSetup"] = 19] = "SOAccountSetup";
    eFeatures[eFeatures["SOAnnouncements"] = 20] = "SOAnnouncements";
    eFeatures[eFeatures["SOServicesContract"] = 21] = "SOServicesContract";
    eFeatures[eFeatures["SOServicesStatus"] = 22] = "SOServicesStatus";
    eFeatures[eFeatures["SORepSettings"] = 23] = "SORepSettings";
    eFeatures[eFeatures["SOSecurity"] = 24] = "SOSecurity";
    eFeatures[eFeatures["CustomsActionScreens"] = 25] = "CustomsActionScreens";
    eFeatures[eFeatures["ClickTracking"] = 26] = "ClickTracking";
    eFeatures[eFeatures["MailMergeTemplates"] = 27] = "MailMergeTemplates";
    eFeatures[eFeatures["EmailTemplates"] = 28] = "EmailTemplates";
    eFeatures[eFeatures["FbcEmailTemplates"] = 29] = "FbcEmailTemplates";
    eFeatures[eFeatures["TextMessageTemplates"] = 30] = "TextMessageTemplates";
    eFeatures[eFeatures["ImageBank"] = 31] = "ImageBank";
    eFeatures[eFeatures["RestoreContact"] = 32] = "RestoreContact";
    eFeatures[eFeatures["MapContact"] = 33] = "MapContact";
    eFeatures[eFeatures["ExcelUploadWizard"] = 34] = "ExcelUploadWizard";
    eFeatures[eFeatures["BulkContactActions"] = 35] = "BulkContactActions";
    eFeatures[eFeatures["ManageDuplicates"] = 36] = "ManageDuplicates";
    eFeatures[eFeatures["WebForm"] = 37] = "WebForm";
    eFeatures[eFeatures["AppointmentTypeSummary"] = 38] = "AppointmentTypeSummary";
    eFeatures[eFeatures["AppointmentsbyTwoDimensions"] = 39] = "AppointmentsbyTwoDimensions";
    eFeatures[eFeatures["QualificationCallReport"] = 40] = "QualificationCallReport";
    eFeatures[eFeatures["NoteTypeSummary"] = 41] = "NoteTypeSummary";
    eFeatures[eFeatures["CallActionButtonClickReport"] = 42] = "CallActionButtonClickReport";
    eFeatures[eFeatures["EmailOpenRateReport"] = 43] = "EmailOpenRateReport";
    eFeatures[eFeatures["CompanyList"] = 44] = "CompanyList";
    eFeatures[eFeatures["LeadCreate"] = 49] = "LeadCreate";
    eFeatures[eFeatures["MyLead"] = 50] = "MyLead";
    eFeatures[eFeatures["CompanyCreate"] = 51] = "CompanyCreate";
    eFeatures[eFeatures["BulkCompaniesAction"] = 52] = "BulkCompaniesAction";
    eFeatures[eFeatures["MyCalender"] = 53] = "MyCalender";
})(eFeatures = exports.eFeatures || (exports.eFeatures = {}));
var eClassCodes;
(function (eClassCodes) {
    eClassCodes[eClassCodes["Class1Code"] = 0] = "Class1Code";
    eClassCodes[eClassCodes["Class2Code"] = 1] = "Class2Code";
    eClassCodes[eClassCodes["Class3Code"] = 2] = "Class3Code";
    eClassCodes[eClassCodes["Class4Code"] = 3] = "Class4Code";
    eClassCodes[eClassCodes["Class5Code"] = 4] = "Class5Code";
    eClassCodes[eClassCodes["Class6Code"] = 5] = "Class6Code";
    eClassCodes[eClassCodes["Class7Code"] = 6] = "Class7Code";
    eClassCodes[eClassCodes["Class8Code"] = 7] = "Class8Code";
})(eClassCodes = exports.eClassCodes || (exports.eClassCodes = {}));
var eAppointmentSettings;
(function (eAppointmentSettings) {
    eAppointmentSettings[eAppointmentSettings["ApptContactTypeCode"] = 0] = "ApptContactTypeCode";
    eAppointmentSettings[eAppointmentSettings["ApptGeneralTypeCode"] = 1] = "ApptGeneralTypeCode";
    eAppointmentSettings[eAppointmentSettings["ApptLeadTypeCode"] = 2] = "ApptLeadTypeCode";
    eAppointmentSettings[eAppointmentSettings["MailingtypeCode"] = 3] = "MailingtypeCode";
    eAppointmentSettings[eAppointmentSettings["NotetypeCode"] = 4] = "NotetypeCode";
})(eAppointmentSettings = exports.eAppointmentSettings || (exports.eAppointmentSettings = {}));
var eLeadSettings;
(function (eLeadSettings) {
    eLeadSettings[eLeadSettings["LeadClass1Code"] = 0] = "LeadClass1Code";
    eLeadSettings[eLeadSettings["LeadClass2Code"] = 1] = "LeadClass2Code";
    eLeadSettings[eLeadSettings["LeadClass3Code"] = 2] = "LeadClass3Code";
    eLeadSettings[eLeadSettings["LeadClass4Code"] = 3] = "LeadClass4Code";
    eLeadSettings[eLeadSettings["LeadClass5Code"] = 4] = "LeadClass5Code";
    eLeadSettings[eLeadSettings["LeadClass6Code"] = 5] = "LeadClass6Code";
    eLeadSettings[eLeadSettings["LeadClass7Code"] = 6] = "LeadClass7Code";
    eLeadSettings[eLeadSettings["LeadClass8Code"] = 7] = "LeadClass8Code";
    eLeadSettings[eLeadSettings["LeadClass9Code"] = 8] = "LeadClass9Code";
    eLeadSettings[eLeadSettings["LeadStatusCode"] = 9] = "LeadStatusCode";
})(eLeadSettings = exports.eLeadSettings || (exports.eLeadSettings = {}));
var webFormAction;
(function (webFormAction) {
    webFormAction[webFormAction["Start"] = 1] = "Start";
    webFormAction[webFormAction["Stop"] = 2] = "Stop";
    webFormAction[webFormAction["Pause"] = 3] = "Pause";
    webFormAction[webFormAction["Remove"] = 2] = "Remove";
})(webFormAction = exports.webFormAction || (exports.webFormAction = {}));
var eCompanySettings;
(function (eCompanySettings) {
    eCompanySettings[eCompanySettings["CoClass1Code"] = 0] = "CoClass1Code";
    eCompanySettings[eCompanySettings["CoClass2Code"] = 1] = "CoClass2Code";
    eCompanySettings[eCompanySettings["CoClass3Code"] = 2] = "CoClass3Code";
    eCompanySettings[eCompanySettings["CoClass4Code"] = 3] = "CoClass4Code";
    eCompanySettings[eCompanySettings["CoClass5Code"] = 4] = "CoClass5Code";
    eCompanySettings[eCompanySettings["CoClass6Code"] = 5] = "CoClass6Code";
    eCompanySettings[eCompanySettings["CoClass7Code"] = 6] = "CoClass7Code";
    eCompanySettings[eCompanySettings["CoClass8Code"] = 7] = "CoClass8Code";
})(eCompanySettings = exports.eCompanySettings || (exports.eCompanySettings = {}));
var eColor;
(function (eColor) {
    eColor[eColor["Red"] = 0] = "Red";
    eColor[eColor["Green"] = 1] = "Green";
    eColor[eColor["Darkgreen"] = 2] = "Darkgreen";
    eColor[eColor["Unknown"] = 3] = "Unknown";
})(eColor = exports.eColor || (exports.eColor = {}));
var eBillingViewMode;
(function (eBillingViewMode) {
    eBillingViewMode[eBillingViewMode["MainView"] = 0] = "MainView";
    eBillingViewMode[eBillingViewMode["UpgradeStart"] = 1] = "UpgradeStart";
    eBillingViewMode[eBillingViewMode["UpgradeConfirm"] = 2] = "UpgradeConfirm";
    eBillingViewMode[eBillingViewMode["UpgradeProcess"] = 3] = "UpgradeProcess";
    eBillingViewMode[eBillingViewMode["UsersStart"] = 4] = "UsersStart";
    eBillingViewMode[eBillingViewMode["UsersConfirm"] = 5] = "UsersConfirm";
    eBillingViewMode[eBillingViewMode["UsersSetup"] = 6] = "UsersSetup";
})(eBillingViewMode = exports.eBillingViewMode || (exports.eBillingViewMode = {}));
var eExportRequestObjectType;
(function (eExportRequestObjectType) {
    eExportRequestObjectType[eExportRequestObjectType["Unknown"] = 0] = "Unknown";
    eExportRequestObjectType[eExportRequestObjectType["Company"] = 1] = "Company";
    eExportRequestObjectType[eExportRequestObjectType["Contact"] = 2] = "Contact";
    eExportRequestObjectType[eExportRequestObjectType["Lead"] = 3] = "Lead";
    eExportRequestObjectType[eExportRequestObjectType["LeadInvoice"] = 31] = "LeadInvoice";
    eExportRequestObjectType[eExportRequestObjectType["Mailing"] = 4] = "Mailing";
    eExportRequestObjectType[eExportRequestObjectType["Campaign_Item"] = 5] = "Campaign_Item";
    eExportRequestObjectType[eExportRequestObjectType["KML_File"] = 9] = "KML_File";
    eExportRequestObjectType[eExportRequestObjectType["Deverus_Activity_Report"] = 101] = "Deverus_Activity_Report";
    eExportRequestObjectType[eExportRequestObjectType["AFH_Activity_Report"] = 200] = "AFH_Activity_Report";
    eExportRequestObjectType[eExportRequestObjectType["SkyRise_Activity_Report"] = 250] = "SkyRise_Activity_Report";
    eExportRequestObjectType[eExportRequestObjectType["Harvest_Business_Lead_Report"] = 300] = "Harvest_Business_Lead_Report";
    eExportRequestObjectType[eExportRequestObjectType["InventHelp_Scorecard_Report"] = 400] = "InventHelp_Scorecard_Report";
    eExportRequestObjectType[eExportRequestObjectType["InventHelp_ScorecardByCode_Report"] = 401] = "InventHelp_ScorecardByCode_Report";
    eExportRequestObjectType[eExportRequestObjectType["InventHelp_ScorecardByKeyword_Report"] = 402] = "InventHelp_ScorecardByKeyword_Report";
    eExportRequestObjectType[eExportRequestObjectType["InventHelp_ScorecardCompare_Report"] = 403] = "InventHelp_ScorecardCompare_Report";
    eExportRequestObjectType[eExportRequestObjectType["InventHelp_ScorecardByTVCode_Report"] = 404] = "InventHelp_ScorecardByTVCode_Report";
    eExportRequestObjectType[eExportRequestObjectType["InventHelp_ScorecardByApptSetter_Report"] = 405] = "InventHelp_ScorecardByApptSetter_Report";
    eExportRequestObjectType[eExportRequestObjectType["FBC_Scorecard_Report"] = 500] = "FBC_Scorecard_Report";
})(eExportRequestObjectType = exports.eExportRequestObjectType || (exports.eExportRequestObjectType = {}));
var eExportRequestStatus;
(function (eExportRequestStatus) {
    eExportRequestStatus[eExportRequestStatus["None"] = 0] = "None";
    eExportRequestStatus[eExportRequestStatus["Pending"] = 1] = "Pending";
    eExportRequestStatus[eExportRequestStatus["InProgress"] = 2] = "InProgress";
    eExportRequestStatus[eExportRequestStatus["Completed"] = 3] = "Completed";
    eExportRequestStatus[eExportRequestStatus["ToBeDeleted"] = 4] = "ToBeDeleted";
    eExportRequestStatus[eExportRequestStatus["Archived"] = 5] = "Archived";
})(eExportRequestStatus = exports.eExportRequestStatus || (exports.eExportRequestStatus = {}));
var CreateExportFor;
(function (CreateExportFor) {
    CreateExportFor[CreateExportFor["Unknown"] = 0] = "Unknown";
    CreateExportFor[CreateExportFor["ScoreCardByCode"] = 1] = "ScoreCardByCode";
})(CreateExportFor = exports.CreateExportFor || (exports.CreateExportFor = {}));
/*Excel Upload Section*/
var eEditType;
(function (eEditType) {
    eEditType[eEditType["Replace"] = 0] = "Replace";
    eEditType[eEditType["AddTo"] = 1] = "AddTo";
    eEditType[eEditType["Clear"] = 2] = "Clear";
    eEditType[eEditType["Remove"] = 3] = "Remove";
})(eEditType = exports.eEditType || (exports.eEditType = {}));
var eUploadContactActionToTake;
(function (eUploadContactActionToTake) {
    eUploadContactActionToTake[eUploadContactActionToTake["DoNotUpload"] = 0] = "DoNotUpload";
    eUploadContactActionToTake[eUploadContactActionToTake["Overwrite"] = 1] = "Overwrite";
    eUploadContactActionToTake[eUploadContactActionToTake["Upload"] = 2] = "Upload";
    eUploadContactActionToTake[eUploadContactActionToTake["None"] = 3] = "None";
})(eUploadContactActionToTake = exports.eUploadContactActionToTake || (exports.eUploadContactActionToTake = {}));
var eTaskCategory;
(function (eTaskCategory) {
    eTaskCategory[eTaskCategory["Unknown"] = 0] = "Unknown";
    eTaskCategory[eTaskCategory["Personal"] = 1] = "Personal";
    eTaskCategory[eTaskCategory["Contact"] = 2] = "Contact";
    eTaskCategory[eTaskCategory["Lead"] = 3] = "Lead";
    eTaskCategory[eTaskCategory["Proposal"] = 4] = "Proposal";
    eTaskCategory[eTaskCategory["Project"] = 5] = "Project";
})(eTaskCategory = exports.eTaskCategory || (exports.eTaskCategory = {}));
var eTaskPriority;
(function (eTaskPriority) {
    eTaskPriority[eTaskPriority["None"] = 0] = "None";
    eTaskPriority[eTaskPriority["Low"] = 1] = "Low";
    eTaskPriority[eTaskPriority["Medium"] = 2] = "Medium";
    eTaskPriority[eTaskPriority["High"] = 3] = "High";
})(eTaskPriority = exports.eTaskPriority || (exports.eTaskPriority = {}));
var eApptCategory;
(function (eApptCategory) {
    eApptCategory[eApptCategory["Personal"] = 0] = "Personal";
    eApptCategory[eApptCategory["Company"] = 1] = "Company";
    eApptCategory[eApptCategory["Contact"] = 2] = "Contact";
    eApptCategory[eApptCategory["Lead"] = 3] = "Lead";
    eApptCategory[eApptCategory["None"] = 4] = "None";
    eApptCategory[eApptCategory["Proposal"] = 5] = "Proposal";
    eApptCategory[eApptCategory["Project"] = 6] = "Project";
    eApptCategory[eApptCategory["CompanyObject"] = 7] = "CompanyObject";
})(eApptCategory = exports.eApptCategory || (exports.eApptCategory = {}));
var eCalCalendar;
(function (eCalCalendar) {
    eCalCalendar[eCalCalendar["User"] = 0] = "User";
    eCalCalendar[eCalCalendar["Team"] = 1] = "Team";
    eCalCalendar[eCalCalendar["Company"] = 2] = "Company";
    eCalCalendar[eCalCalendar["Office"] = 3] = "Office";
})(eCalCalendar = exports.eCalCalendar || (exports.eCalCalendar = {}));
var eDDField;
(function (eDDField) {
    eDDField[eDDField["Unknown"] = 0] = "Unknown";
    eDDField[eDDField["CoClass1Code"] = 1] = "CoClass1Code";
    eDDField[eDDField["CoClass2Code"] = 2] = "CoClass2Code";
    eDDField[eDDField["CoClass3Code"] = 3] = "CoClass3Code";
    eDDField[eDDField["CoClass4Code"] = 4] = "CoClass4Code";
    eDDField[eDDField["CoClass5Code"] = 5] = "CoClass5Code";
    eDDField[eDDField["CoClass6Code"] = 6] = "CoClass6Code";
    eDDField[eDDField["CoClass7Code"] = 7] = "CoClass7Code";
    eDDField[eDDField["CoClass8Code"] = 8] = "CoClass8Code";
    eDDField[eDDField["Class1Code"] = 11] = "Class1Code";
    eDDField[eDDField["Class2Code"] = 12] = "Class2Code";
    eDDField[eDDField["Class3Code"] = 13] = "Class3Code";
    eDDField[eDDField["Class4Code"] = 14] = "Class4Code";
    eDDField[eDDField["Class5Code"] = 15] = "Class5Code";
    eDDField[eDDField["Class6Code"] = 16] = "Class6Code";
    eDDField[eDDField["Class7Code"] = 17] = "Class7Code";
    eDDField[eDDField["Class8Code"] = 18] = "Class8Code";
    eDDField[eDDField["Multi1Code"] = 19] = "Multi1Code";
    eDDField[eDDField["Multi2Code"] = 110] = "Multi2Code";
    eDDField[eDDField["Multi3Code"] = 111] = "Multi3Code";
    eDDField[eDDField["Multi4Code"] = 112] = "Multi4Code";
    eDDField[eDDField["LeadClass1Code"] = 20] = "LeadClass1Code";
    eDDField[eDDField["LeadClass2Code"] = 21] = "LeadClass2Code";
    eDDField[eDDField["LeadClass3Code"] = 22] = "LeadClass3Code";
    eDDField[eDDField["LeadClass4Code"] = 23] = "LeadClass4Code";
    eDDField[eDDField["LeadClass5Code"] = 24] = "LeadClass5Code";
    eDDField[eDDField["LeadClass6Code"] = 25] = "LeadClass6Code";
    eDDField[eDDField["LeadClass7Code"] = 26] = "LeadClass7Code";
    eDDField[eDDField["LeadClass8Code"] = 27] = "LeadClass8Code";
    eDDField[eDDField["LeadClass9Code"] = 28] = "LeadClass9Code";
    eDDField[eDDField["LeadMulti1Code"] = 210] = "LeadMulti1Code";
    eDDField[eDDField["LeadMulti2Code"] = 211] = "LeadMulti2Code";
    eDDField[eDDField["LeadMulti3Code"] = 212] = "LeadMulti3Code";
    eDDField[eDDField["LeadMulti4Code"] = 213] = "LeadMulti4Code";
    eDDField[eDDField["LeadStatusCode"] = 214] = "LeadStatusCode";
    eDDField[eDDField["TeamCode"] = 500] = "TeamCode";
    eDDField[eDDField["OfficeCode"] = 600] = "OfficeCode";
    eDDField[eDDField["ApptGeneralTypeCode"] = 700] = "ApptGeneralTypeCode";
    eDDField[eDDField["ApptContactTypeCode"] = 701] = "ApptContactTypeCode";
    eDDField[eDDField["ApptLeadTypeCode"] = 702] = "ApptLeadTypeCode";
    eDDField[eDDField["ApptProposalTypeCode"] = 703] = "ApptProposalTypeCode";
    eDDField[eDDField["ApptProjectTypeCode"] = 704] = "ApptProjectTypeCode";
    eDDField[eDDField["NoteTypeCode"] = 800] = "NoteTypeCode";
    eDDField[eDDField["MailingTypeCode"] = 900] = "MailingTypeCode";
})(eDDField = exports.eDDField || (exports.eDDField = {}));
var eGoalType;
(function (eGoalType) {
    eGoalType[eGoalType["None"] = 0] = "None";
    eGoalType[eGoalType["ApptGeneralType"] = 1] = "ApptGeneralType";
    eGoalType[eGoalType["ApptContactType"] = 2] = "ApptContactType";
    eGoalType[eGoalType["ApptLeadType"] = 3] = "ApptLeadType";
    eGoalType[eGoalType["ApptProposalType"] = 4] = "ApptProposalType";
    eGoalType[eGoalType["ApptProjectType"] = 5] = "ApptProjectType";
    eGoalType[eGoalType["NewLeads"] = 6] = "NewLeads";
    eGoalType[eGoalType["LeadRevenueGross"] = 7] = "LeadRevenueGross";
    eGoalType[eGoalType["LeadRevenueNet"] = 8] = "LeadRevenueNet";
    eGoalType[eGoalType["NewContacts"] = 9] = "NewContacts";
    eGoalType[eGoalType["LeadStatus"] = 10] = "LeadStatus";
    eGoalType[eGoalType["Class1Code"] = 11] = "Class1Code";
    eGoalType[eGoalType["Class2Code"] = 12] = "Class2Code";
    eGoalType[eGoalType["Class3Code"] = 13] = "Class3Code";
    eGoalType[eGoalType["Class4Code"] = 14] = "Class4Code";
    eGoalType[eGoalType["Class5Code"] = 15] = "Class5Code";
    eGoalType[eGoalType["Class6Code"] = 16] = "Class6Code";
    eGoalType[eGoalType["Class7Code"] = 17] = "Class7Code";
    eGoalType[eGoalType["Class8Code"] = 18] = "Class8Code";
    eGoalType[eGoalType["LeadClass1Code"] = 20] = "LeadClass1Code";
    eGoalType[eGoalType["LeadClass2Code"] = 21] = "LeadClass2Code";
    eGoalType[eGoalType["LeadClass3Code"] = 22] = "LeadClass3Code";
    eGoalType[eGoalType["LeadClass4Code"] = 23] = "LeadClass4Code";
    eGoalType[eGoalType["LeadClass5Code"] = 24] = "LeadClass5Code";
    eGoalType[eGoalType["LeadClass6Code"] = 25] = "LeadClass6Code";
    eGoalType[eGoalType["LeadClass7Code"] = 26] = "LeadClass7Code";
    eGoalType[eGoalType["LeadClass8Code"] = 27] = "LeadClass8Code";
    eGoalType[eGoalType["LeadClass9Code"] = 28] = "LeadClass9Code";
})(eGoalType = exports.eGoalType || (exports.eGoalType = {}));
var eGoalTypeCategory;
(function (eGoalTypeCategory) {
    eGoalTypeCategory[eGoalTypeCategory["None"] = 0] = "None";
    eGoalTypeCategory[eGoalTypeCategory["ApptGeneralType"] = 1] = "ApptGeneralType";
    eGoalTypeCategory[eGoalTypeCategory["ApptContactType"] = 2] = "ApptContactType";
    eGoalTypeCategory[eGoalTypeCategory["ApptLeadType"] = 3] = "ApptLeadType";
    eGoalTypeCategory[eGoalTypeCategory["ApptProposalType"] = 4] = "ApptProposalType";
    eGoalTypeCategory[eGoalTypeCategory["ApptProjectType"] = 5] = "ApptProjectType";
    eGoalTypeCategory[eGoalTypeCategory["General"] = 6] = "General";
    eGoalTypeCategory[eGoalTypeCategory["LeadStatus"] = 10] = "LeadStatus";
    eGoalTypeCategory[eGoalTypeCategory["Class1Code"] = 11] = "Class1Code";
    eGoalTypeCategory[eGoalTypeCategory["Class2Code"] = 12] = "Class2Code";
    eGoalTypeCategory[eGoalTypeCategory["Class3Code"] = 13] = "Class3Code";
    eGoalTypeCategory[eGoalTypeCategory["Class4Code"] = 14] = "Class4Code";
    eGoalTypeCategory[eGoalTypeCategory["Class5Code"] = 15] = "Class5Code";
    eGoalTypeCategory[eGoalTypeCategory["Class6Code"] = 16] = "Class6Code";
    eGoalTypeCategory[eGoalTypeCategory["Class7Code"] = 17] = "Class7Code";
    eGoalTypeCategory[eGoalTypeCategory["Class8Code"] = 18] = "Class8Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass1Code"] = 20] = "LeadClass1Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass2Code"] = 21] = "LeadClass2Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass3Code"] = 22] = "LeadClass3Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass4Code"] = 23] = "LeadClass4Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass5Code"] = 24] = "LeadClass5Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass6Code"] = 25] = "LeadClass6Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass7Code"] = 26] = "LeadClass7Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass8Code"] = 27] = "LeadClass8Code";
    eGoalTypeCategory[eGoalTypeCategory["LeadClass9Code"] = 29] = "LeadClass9Code";
})(eGoalTypeCategory = exports.eGoalTypeCategory || (exports.eGoalTypeCategory = {}));
var eCalenderView;
(function (eCalenderView) {
    eCalenderView[eCalenderView["Month"] = 0] = "Month";
    eCalenderView[eCalenderView["Day"] = 1] = "Day";
    eCalenderView[eCalenderView["Week"] = 2] = "Week";
})(eCalenderView = exports.eCalenderView || (exports.eCalenderView = {}));
var eTaskStatus;
(function (eTaskStatus) {
    eTaskStatus[eTaskStatus["Pending"] = 0] = "Pending";
    eTaskStatus[eTaskStatus["Completed"] = 1] = "Completed";
    eTaskStatus[eTaskStatus["OnHold"] = 2] = "OnHold";
    eTaskStatus[eTaskStatus["None"] = 3] = "None";
    eTaskStatus[eTaskStatus["ToBeDeleted"] = 9] = "ToBeDeleted";
})(eTaskStatus = exports.eTaskStatus || (exports.eTaskStatus = {}));
var eMailingStatus;
(function (eMailingStatus) {
    eMailingStatus[eMailingStatus["Pending"] = 0] = "Pending";
    eMailingStatus[eMailingStatus["Cancelled"] = 1] = "Cancelled";
    eMailingStatus[eMailingStatus["Completed"] = 2] = "Completed";
    eMailingStatus[eMailingStatus["None"] = 3] = "None";
    eMailingStatus[eMailingStatus["In_Process"] = 4] = "In_Process";
    eMailingStatus[eMailingStatus["Awaiting_MMDoc"] = 5] = "Awaiting_MMDoc";
    eMailingStatus[eMailingStatus["Awaiting_Configuration"] = 6] = "Awaiting_Configuration";
    eMailingStatus[eMailingStatus["Being_Configured"] = 7] = "Being_Configured";
})(eMailingStatus = exports.eMailingStatus || (exports.eMailingStatus = {}));
var eApptStatus;
(function (eApptStatus) {
    eApptStatus[eApptStatus["Pending"] = 0] = "Pending";
    eApptStatus[eApptStatus["Cancelled"] = 1] = "Cancelled";
    eApptStatus[eApptStatus["Completed"] = 2] = "Completed";
    eApptStatus[eApptStatus["None"] = 3] = "None";
    eApptStatus[eApptStatus["Bumped"] = 4] = "Bumped";
    eApptStatus[eApptStatus["CompleteAndCampaignStop"] = 5] = "CompleteAndCampaignStop";
    eApptStatus[eApptStatus["ToBeDeleted"] = 9] = "ToBeDeleted";
})(eApptStatus = exports.eApptStatus || (exports.eApptStatus = {}));
var eReportFilterBy;
(function (eReportFilterBy) {
    eReportFilterBy[eReportFilterBy["All"] = 0] = "All";
    eReportFilterBy[eReportFilterBy["User"] = 1] = "User";
    eReportFilterBy[eReportFilterBy["Team"] = 2] = "Team";
    eReportFilterBy[eReportFilterBy["Office"] = 3] = "Office";
})(eReportFilterBy = exports.eReportFilterBy || (exports.eReportFilterBy = {}));
var eReportTimePeriod;
(function (eReportTimePeriod) {
    eReportTimePeriod[eReportTimePeriod["n0to3"] = 1] = "n0to3";
    eReportTimePeriod[eReportTimePeriod["n3to6"] = 2] = "n3to6";
    eReportTimePeriod[eReportTimePeriod["n6to12"] = 3] = "n6to12";
    eReportTimePeriod[eReportTimePeriod["nYTD"] = 4] = "nYTD";
    eReportTimePeriod[eReportTimePeriod["nThisYear"] = 5] = "nThisYear";
    eReportTimePeriod[eReportTimePeriod["nLastYear"] = 6] = "nLastYear";
    eReportTimePeriod[eReportTimePeriod["nSpecificDates"] = 7] = "nSpecificDates";
})(eReportTimePeriod = exports.eReportTimePeriod || (exports.eReportTimePeriod = {}));
var eMeasure;
(function (eMeasure) {
    eMeasure[eMeasure["NumLeads"] = 0] = "NumLeads";
    eMeasure[eMeasure["Volume"] = 1] = "Volume";
    eMeasure[eMeasure["Revenue"] = 2] = "Revenue";
    eMeasure[eMeasure["CustomMoney1"] = 3] = "CustomMoney1";
    eMeasure[eMeasure["CustomMoney2"] = 4] = "CustomMoney2";
    eMeasure[eMeasure["CustomMoney3"] = 5] = "CustomMoney3";
    eMeasure[eMeasure["CustomMoney4"] = 6] = "CustomMoney4";
})(eMeasure = exports.eMeasure || (exports.eMeasure = {}));
var SearchContactBy;
(function (SearchContactBy) {
    SearchContactBy[SearchContactBy["ClickTracking"] = 1] = "ClickTracking";
    SearchContactBy[SearchContactBy["Referral"] = 2] = "Referral";
    SearchContactBy[SearchContactBy["Referrer"] = 3] = "Referrer";
    SearchContactBy[SearchContactBy["TagCloud"] = 4] = "TagCloud";
})(SearchContactBy = exports.SearchContactBy || (exports.SearchContactBy = {}));
//# sourceMappingURL=enum.model.js.map